version: '3.9'
services:
  metabase-mysql1:
    image: metabase/metabase-enterprise:v1.48.8
    container_name: metabase-mysql1
    hostname: metabase-mysql1
    volumes: 
    - /dev/urandom:/dev/random:ro
    ports:
      - 3000:3000
    environment:
      MB_DB_DBNAME: "metabase"
      MB_DB_PORT: "3306"
      MB_DB_USER: "metabase"
      MB_DB_PASS: "mysecretpassword"
      MB_DB_HOST: "mysql-app-db"
      MB_DB_TYPE: "mysql"
      MB_EMAIL_SMTP_HOST: maildev-sub
      MB_EMAIL_SMTP_PASSWORD: password
      MB_EMAIL_SMTP_PORT: 1025
      MB_EMAIL_SMTP_SECURITY: none
      MB_EMAIL_SMTP_USERNAME: admin
      JAVA_TOOL_OPTIONS: -Xmx1488m -Xms500m 
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 3072M
        reservations:
          cpus: '1'
          memory: 1536M
    networks: 
      - metanet1-mysql
    healthcheck:
      test: curl --fail -X GET -I http://localhost:3000/api/health || exit 1
      interval: 15s
      timeout: 30s
      retries: 10
  proxysql:
    image: proxysql/proxysql:2.6.0
    container_name: proxysql
    hostname: proxysql
    ports:
      - 6033:6033
    volumes:
      - $PWD/proxysql/proxysql.cnf:/etc/proxysql.cnf:ro
    networks:
    - metanet1-mysql
    depends_on:
      - mysql-data
  mysql-app-db:
    image: mariadb:11.2.2
    container_name: mysql-app-db
    hostname: mysql-app-db
    ports:
      - 3306:3306
    environment:
      - "MYSQL_ROOT_PASSWORD=mysecretpassword"
      - "MYSQL_USER=metabase"
      - "MYSQL_PASSWORD=mysecretpassword"
      - "MYSQL_DATABASE=metabase"
    volumes:
      # - $PWD/mysql-data:/var/lib/mysql
      - $PWD/mysql-app-db-config/my.cnf:/etc/mysql/conf.d/my.cnf:ro
    networks: 
      - metanet1-mysql
  setup-mysql:
    build: setup/.
    container_name: setup-postgres
    volumes:
      - $PWD/setup/setup.py:/app/setup.py
    networks:
      - metanet1-mysql
    depends_on:
      metabase-mysql1:
        condition: service_healthy
    command: python /app/setup.py
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 64M
        reservations:
          cpus: '0.5'
          memory: 32M
    environment:
      host: http://metabase-mysql1
      port: 3000
      dbs: 1
  mysql-data:
    image: metabase/qa-databases:mysql-sample-8
    container_name: mysql-data1
    hostname: mysql-data1
    ports:
      - 3308:3306
    networks: 
      - metanet1-mysql
    volumes:
      - $PWD/mysql-config/my.cnf:/etc/mysql/conf.d/my.cnf:ro
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
  maildev-sub-postgres:
    image: maildev/maildev:2.1.0
    container_name: maildev-sub-postgres
    hostname: maildev-sub
    ports:
    - "3003:1080"
    networks:
    - metanet1-mysql
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 64M
        reservations:
          cpus: '0.5'
          memory: 32M
networks: 
  metanet1-mysql:
    driver: bridge